### ISSUE TITLE
Defanged first.last Email Addresses do not refang correctly

### ISSUE THREAD

**Issue by bradchiappetta** [InQuest/python-iocextract#36]
Issue seems to be around this defangged format:

`firstname[.]lastname[@]domainname[.]org`

When refanged, seeing the following:

`lastname@domainman.org`

For some reason, the username format of first.last is getting chopped off to just last.

**Comment by bradchiappetta** [comment]
Actually, this might be an email parser issue in general.  I just retested with refang disabled, and I get

`lastname[@]domainname[.]org`

**Comment by azazelm3dj3d** [comment]
New version is now available on PyPI: https://pypi.org/project/iocextract/1.14.0/
