### ISSUE TITLE
File redirection doesn't work

### ISSUE THREAD

**Issue by sooshie** [InQuest/python-iocextract#37]
If I run `iocextract.py --input info.txt` it will correctly print indicators to what seems to be standard out, however `iocextract.py --input info.txt | less` simply gives the the "you've got nothing `END`" in _less_. It looks like however you're getting the handle to STDOUT isn't the actual STDOUT handle.

Tested on OS X 10.14.6 with Python 3.7.6.

**Comment by presianbg** [comment]
Same on linux.

**Comment by azazelm3dj3d** [comment]
Hi @sooshie,

Thanks to @presianbg's fix (https://github.com/InQuest/python-iocextract/pull/48) this issue should now be resolved in development. I will ping this issue once more when a new package is available from PyPI.

**Comment by azazelm3dj3d** [comment]
The new PyPI package is now available!

PyPI: https://pypi.org/project/iocextract/1.13.8/
GitHub Releases: https://github.com/InQuest/python-iocextract/releases/tag/v1.13.8
