### ISSUE TITLE
Failed to extract the URLs from this tweet

### ISSUE THREAD

**Issue by shankaraman** [InQuest/python-iocextract#42]
The URLs from this [tweet](https://twitter.com/ReBensk/status/1262676640074657793) were not extracted by the tool. 

I [tried](https://pastebin.com/UiYhKSxw) all the methods : extract_urls, extract_unencoded_urls, extract_encoded_urls , none of them worked. Is there a way to fix it ?

**Comment by cmmorrow** [comment]
Hello @shankaraman, I think the problem is because the tweet has defanging brackets around the colon ":" character which is not in the iocextract refanging regular expression for URLs. I can work on adding this pattern to the regular expression.

**Comment by cmmorrow** [comment]
Hello @shankaraman, I have a fix merged to master. You can check to see if this works by pulling the master branch and running `iocextract.py`. This change will be included in a future release.

**Comment by shankaraman** [comment]
Thank you very much @cmmorrow , I shall test the latest commit and get back to you with a feedback. And thanks for your time too!

**Comment by shankaraman** [comment]
Hello @cmmorrow , please check the 1st column

![Screenshot from 2020-05-25 16-23-30](https://user-images.githubusercontent.com/811541/82816842-8caa0800-9ea4-11ea-8994-d584722a9d4b.png)

**Comment by cmmorrow** [comment]
Thanks for catching that @shankaraman. I've corrected the issue and pushed the change to master. Please review and let me know if you notice any problems.

**Comment by shankaraman** [comment]
Works like a charm! 

Thanks!
