### ISSUE TITLE
'https' scheme values defanged as HXXPS are refanged as 'http'

### ISSUE THREAD

**Issue by dsfinn** [InQuest/python-iocextract#49]
As in title; e.g.

`'hxxps://example.com'` is refanged as `'http://example.com'`

**Comment by dsfinn** [comment]
Pull Request: #50

**Comment by azazelm3dj3d** [comment]
Hi, @dsfinn,

This issue has been merged and tested. I will ping this issue once more when a new PyPI package is available.

**Comment by azazelm3dj3d** [comment]
The new PyPI package is now available!

PyPI: https://pypi.org/project/iocextract/1.13.8/
GitHub Releases: https://github.com/InQuest/python-iocextract/releases/tag/v1.13.8
