### ISSUE TITLE
catastrophic backtracking in BACKSLASH_URL_RE

### ISSUE THREAD

**Issue by DaveCrim** [InQuest/python-iocextract#52]
Pretty much the title, discovered this in a downstream project, https://github.com/s0md3v/Photon, commented on it there as well.  Thought I'd leave the comment here too, the rest of the defang RE seem to work fine, but the backslash one seemed to cause a lot of hangs when I was using it.  

Test against: http://myexample.com/dir/../path/escaping/../too/many/../dots/../in/../the/path/../cause/this/to/fail

**Comment by azazelm3dj3d** [comment]
Hi, @DaveCrim!

PR just merged to resolve this issue. I'll ping this issue once more when a new package is available on PyPI for download.

**Comment by azazelm3dj3d** [comment]
The new PyPI package is now available!

PyPI: https://pypi.org/project/iocextract/1.13.8/
GitHub Releases: https://github.com/InQuest/python-iocextract/releases/tag/v1.13.8
